name: love_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.2
  lottie: ^3.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie_animated_splash_screen.json
    - assets/drop_purple_water.json
    - assets/icon_app.png
    - assets/bg_icon.png
    - assets/native_splash.png
    - assets/google_fonts/
